import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMail
} from "react-icons/ai";
import { Link, animateScroll as scroll } from "react-scroll";
import { SiC, SiDocker, SiGooglecloud, 
         SiJava, 
         SiJavascript, 
         SiKubernetes,
         SiMongodb,
         SiMysql,
         SiPostgresql,
         SiPrometheus,
         SiPython,
         SiReact,
         SiSpringboot,
         SiVuedotjs
} from "react-icons/si";
import ingunn from "../public/portfolio2.jpeg";
import Image from "next/image";
import PortfolioBox from "../components/portfoliobox";
import { useState } from "react";

export default function Home() {
  const [activeTab, setActiveTab] = useState('home');


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white-500" >
        <div className="bg-rose-100 md:px-20 lg:px-40 px-1">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <ul className="flex items-center">
  
                <li>
                  <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out text-rose-900">
                  <Link className="text-2xl bg-gradient-to-r px-4 py-2 border-none rounded-md ml-8"
                    to="my-projects"
                    spy={true}
                    smooth={true}
                    offset={0}
                    duration={500}
                  >
                    Projects
                  </Link>
                  </div>
                </li>
                <li>
                  <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out text-rose-900">
                  <Link className="text-2xl bg-gradient-to-r px-4 py-2 border-none rounded-md ml-8"
                    to="my-toolbox"
                    spy={true}
                    smooth={true}
                    offset={0}
                    duration={500}
                  >
                    Toolbox
                  </Link>
                  </div>
                </li>
             
            </ul>
          </nav>
          <div className="mx-auto rounded-full w-50 h-50 relative overflow-hidden md:mt-20 md:h-72 md:w-72 h-36 w-36" id="home" >
              <Image src={ingunn} layout="fill" objectFit="cover" />
            </div>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-indigo-700 font-medium md:text-6xl">
              Hi, I'm Ingunn.
            </h2>
            <p className="text-md py-5 leading-8 text-gray-800 max-w-xl mx-auto md:text-xl">
            I'm an incubating Software Engineer currently pursuing a Master of Computer Science at TU Berlin. You can find me at the bouldering gym or in the nearest lake.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-rose-900">
              <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out">
                <a href="mailto:ingunn.flovig@gmail.com"><AiFillMail /></a>
              </div>
              <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out">
              <a href="https://github.com/ingunnaf"><AiFillGithub /></a>
              </div>
              <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out">
                <a href="https://www.linkedin.com/in/ingunnflovig/"><AiFillLinkedin /></a>
              </div>
            </div>
            
          </div>
        </section>
        </div>
        <div className="md:px-20 lg:px-40 px-10" id="my-projects">
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 text-indigo-700">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Over the years, I've built numerous student and personal projects. Here you can find some of my favourites and all the most recent ones.
            </p>
          </div>
          <div className="flex flex-col flex-wrap sm:flex-row gap-10 py-10">
          
          <PortfolioBox
            title={"Elastic Scaling of a Microservice Application"}
            aboutProject={"Implemented Prometheus metric collection for our bottleneck microservices, and autoscaling with KEDA."}
            imagePath={"/../public/microservice2.jpg"}
            icons={[SiGooglecloud, SiKubernetes, SiPrometheus]}
          ></PortfolioBox>

          <PortfolioBox
            title={"Mensa Telegram Bot"}
            aboutProject={"Fetches the weekly menu from the Mensa (German cafeteria) and sends it to you once a week."}
            imagePath={"/../public/telegram-bot.png"}
            icons={[SiPython]}
          ></PortfolioBox>

          <PortfolioBox
            title={"6G Dashboard - Backend"}
            aboutProject={"Built the backend for a dashboard that allows monitoring 6G components and their communication."}
            imagePath={"/../public/dashboard.jpg"}
            icons={[SiJava, SiSpringboot, SiDocker]}
          ></PortfolioBox>
          
          <PortfolioBox
            title={"Sustainability Portal - Backend"}
            aboutProject={"A Sustainability Portal developed for the Norwegian Brønnøysundsregistrene - showcasing public data about sustainability in the fish farming industry in Norway."}
            imagePath={"/../public/baerekraft2.jpeg"}
            icons={[SiPython, SiPostgresql, SiDocker]}
          ></PortfolioBox>
          <PortfolioBox
            title={"Expendibots AI Algorithm"}
            aboutProject={"An algorithm that plays the game expendibots. Uses depth first search to search for an advantageous future game state using heuristic evaluation of game states to limit the search space."}
            imagePath={"/../public/algorithm.jpg"}
            icons={[SiPython]}
          ></PortfolioBox>



          </div>
          
        </section>
        </div>

        <div className="md:px-20 lg:px-40 px-10 mb-10" id="my-toolbox">
        <section>
            <h3 className="text-3xl py-1 text-indigo-700">Toolbox</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I've used numerous languages and tools in my projects, but these are the ones I am most proficient with.</p>
          
          <div className="flex flex-wrap sm:flex-row">

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                <SiSpringboot />
                </div>
                <h3 className="text-lg font-medium text-center">Java & Springboot</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                <SiPython />
                </div>
                <h3 className="text-lg font-medium text-center">Python & Flask</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiPostgresql />
                </div>
                <h3 className="text-lg font-medium text-center">PostgreSQL</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiMongodb />
                </div>
                <h3 className="text-lg font-medium text-center">MongoDB</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiDocker />
                </div>
                <h3 className="text-lg font-medium text-center">Docker</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                <SiKubernetes />
                </div>
                <h3 className="text-lg font-medium text-center">Kubernetes</h3>
              </div>
            </div>

          </div>

          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">I also use these sometimes, but with a higher frequency of Stackoverflow visits and ChatGPT queries.</p>
          <div className="flex flex-wrap sm:flex-row">

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiC />
                </div>
                <h3 className="text-lg font-medium text-center">C</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiReact />
                </div>
                <h3 className="text-lg font-medium text-center">React</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiVuedotjs />
                </div>
                <h3 className="text-lg font-medium text-center">Vue</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiMysql />
                </div>
                <h3 className="text-lg font-medium text-center">MySQL</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                <SiJavascript />
                </div>
                <h3 className="text-lg font-medium text-center">Javascript</h3>
              </div>
            </div>

            <div className="border rounded-lg p-4 transition duration-300 ease-in-out transform hover:shadow-lg flex flex-row justify-center items-center bg-indigo-50 rounded-lg p-4 pb-3 mb-5 mr-5" style={{ width: '125px' }}>
              <div className="flex flex-col justify-center items-center">
                <div className="text-4xl text-rose-900 mb-2">
                  <SiGooglecloud />
                </div>
                <h3 className="text-lg font-medium text-center">Google Cloud</h3>
              </div>
            </div>

          </div>
        </section>
        </div>

        <div className="bg-rose-100 md:px-20 lg:px-40 px-10 ">
          <section>
            <div className=" flex justify-center gap-16 py-3 ">
              <h3 className="text-lg font-medium pt-8 pb-2 text-indigo-700">Get in touch via email or go to my socials with the links below.</h3>    
            </div>

            <div className="text-5xl flex justify-center gap-16 py-3 text-rose-900 pb-10">
              <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out">
                <a href="mailto:ingunn.flovig@gmail.com"><AiFillMail /></a>
              </div>
              <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out">
              <a href="https://github.com/ingunnaf"><AiFillGithub /></a>
              </div>
              <div className="hover:text-indigo-700 hover:scale-110 transition duration-300 ease-in-out">
                <a href="https://www.linkedin.com/in/ingunnflovig/"><AiFillLinkedin /></a>
              </div>
            </div>

          </section>
        </div>
        
      </main>
    </div>
  );
}
